name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_ID: ${{ secrets.USER_ID }}
      TEMPLATE_CONTACT: ${{ secrets.TEMPLATE_CONTACT }}
      CONTACT_SERVICE: ${{ secrets.CONTACT_SERVICE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add other steps for your build process

      - name: Deploy to GitHub Pages
        run: |
          # Your deployment commands here
